name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.2.0,<0.3.0
  - jupyterlite-xeus>=0.1.2,<0.2
  # Additional dependencies for analytics packages
  #- plotly-express
  - libgcc-ng
  - libstdcxx-ng
  - python-dateutil
  - python_abi
  - pytz
  - udatetime
  - matplotlib-base
  - dataclasses
  - datasets
  - filelock
  - importlib_metadata
  # Add dependencies for webscraping
  - pillow
  - beautifulsoup4
  - requests-wasm-polyfill
  - huggingface_hub
  # - packaging
  # - pytorch
  # - pyyaml
  # - regex !=2019.12.17
  # - sacremoses
  # - tokenizers
  #- bs4
  #- requests
  #- tqdm
  #- wordcloud
  #- transformers

