name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.2.0,<0.3.0
  - jupyterlite-xeus>=0.1.2,<0.2
  # Try adding dependencies here
  - libgcc-ng
  - libstdcxx-ng
  - python-dateutil
  - python_abi
  - pytz
  - udatetime
