name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.2.0,<0.3.0
  - jupyterlite-xeus>=0.1.2,<0.2
  # Additional dependencies for analytics packages
  - libgcc-ng
  - libstdcxx-ng
  - python-dateutil
  - python_abi
  - pytz
  - udatetime
  # Add dependencies for webscraping
  - bs4
  - requests
  - wordcloud
  - transformers
  - pyyaml>=6.0.1

