name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  # Add dependencies for analytics
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - bs4
  - requests
  - tqdm
  #- plotly-express
